### ISSUE TITLE
Create readme to help with building the project

### ISSUE THREAD

**Issue by Shrafe** [myellen42/imperial-assault-calculator#1]
Hi there! I'm an avid player of imperial assault and I'd love to contribute! Problem is I'm not experience with web dev and thus have no idea how to build this project, so I can't create PRs! I'm doing some research into how to get started, so if I figure it out I'll create a PR for a README ;)

**Comment by mattyellen** [comment]
That's a good idea.  I should be able to get that done soon.  In the mean time I updated it with the link to the public page so it's at least easier for people to find and use.

**Comment by baptistemanson** [comment]
Hi guys, I have updated the readme on my fork if you are interested.
@mattyellen I can do a PR if you want to!

**Comment by mattyellen** [comment]
Thanks @baptistemanson.  I ended up adding my own since I made a few changes to the build process like swapping out tsd for typings.
