### ISSUE TITLE
jspm update blows up aurelia-bootstrapper & build process

### ISSUE THREAD

**Issue by christopheremmick** [myellen42/imperial-assault-calculator#3]
I wanted to add a 3rd-party jspm package to my fork. Any `jspm install` runs `jspm dl-loader`, which does significant changes to the jspm files in the root jspm_packages folder. (`es6-module-loader` is removed, new files added, etc.) The new version of jspm loads packages differently than before, and it causes aurelia-bootstrapper to fail when trying to load aurelia-templating packages.

The workaround I had to do was to install my wanted package and then manually revert all the jspm loader files back to the older version.

I don't know enough about jspm to fix it. Is this because of forced package dependencies?

**Comment by mattyellen** [comment]
I've updated several packages including all of Aurelia.  Also purged jspm_packages from the repo (except of a couple required packages in gh-pages) and did some other cleanup.  This should resolve the issue you were seeing.
