### ISSUE TITLE
typings folder needs tsd reinstall

### ISSUE THREAD

**Issue by christopheremmick** [myellen42/imperial-assault-calculator#4]
I guess `tsd` has also been updated since the last major build of this project. build-ts in the gulp build task would fail: 

> File 'typings/tsd/tsd.d.ts' not found".

The fix was to run `tsd rebuild`. On my system, I had to `sudo tsd rebuild` and then fix the file permissions on the new typings/tsd folder. I can create a pull request with the new typings folder if you'd like.

**Comment by mattyellen** [comment]
I've swapped out tsd for [typings](https://github.com/typings/typings) since the former is now deprecated.  I also updated a whole bunch of packages.  Things seems to be working well now, but let me know if you still see issues.
