### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by linglo** [myellen42/imperial-assault-calculator#5]
I love this app and want to use it as a base to create a similar tool for Descent. Would it be possible for you to specify a license so I know what I can and can't do with it.

**Comment by mattyellen** [comment]
Sorry, been neglecting this for a while.  Added the license.

Shouldn't be difficult to modify this for Descent.  I actually originally build a stand alone Descent calculator in WPF, but by the time I got around to porting it to a web app my group had switched to Imperial Assault.

**Comment by linglo** [comment]
Thank you so much!  I discovered shortly after I logged this issue that it has already been done, see https://chaoschaoticus.github.io/Descent-Damage-Calculator/#/.
